name: Slash Command Dispatch Example
on:
  pull_request_review_comment:
    types: ["created"]
permissions:
  actions: write
jobs:
  commandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: command-dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with: 
          token: ${{ secrets.TOKEN }}
          permission: none
          commands: |
            preview
          static-args: |
            some=value
            hello=yeet
            lorem
            ${{github.event.pull_request.number}}
            ${{github.event.pull_request.head.sha}}
