name: Slash Command Dispatch Example
on:
  pull_request_review_comment:
    types: ["created"]
permissions:
  actions: write
jobs:
  commandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/slash-command-dispatch@v3
        with: 
          token: ${{ secrets.TOKEN }}
          commands: |
            preview 
          static-args: |
            production
            region=us-east-1
          issue-type: pull-request
          reaction: false

