name: Slash Command Dispatch Example
on:
  issue_comment:
    types: ["created"]
permissions: write-all
jobs:
  commandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.TOKEN}}
      - uses: peter-evans/slash-command-dispatch@v3
        with: 
          token: ${{ secrets.TOKEN }}
          permissions: none
          commands: |
            preview
          static-args: |
            production
      - run: |
          echo "${{toJSON(github.event)}}"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          labels: preview-link
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: pr-${{github.event.issue.number}}
          force_push_tag: true
          message: "Latest release"
