name: Slash Command Dispatch Example
on:
  issue_comment:
    types: ["created"]
  pull_request_review_comment:
    types: ["created"]
permissions:
  actions: write
jobs:
  commandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: command-dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with: 
          commands: |
            preview
          token: ${{ secrets.TOKEN }}
          permission: none
