name: Slash Command Dispatch Example
on:
  issue_comment:
    types: ["created"]
jobs:
  commandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/slash-command-dispatch@v3
        with: 
          token: ${{ secrets.TOKEN }}
          permissions: none
          commands: |
            preview
          static-args: |
            production
      - run: |
          echo "${{github.event_name}}"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          labels: preview-link
      - uses: rickstaa/action-create-tag@v1
        with:
            tag: pr-${{ github.event.issue.number }}
            force_push_tag: true
