name: Slash Command Dispatch Example
on:
  issue_comment:
    types: ["created"]
  pull_request_review_comment:
    types: ["created"]
permissions:
  actions: write
jobs:
  commandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/slash-command-dispatch@v3
        with: 
          token: ${{ secrets.TOKEN }}
          permissions: none
          commands: |
            preview
          static-args: |
            production
            pr=${{toJSON(github.event.pull_request)}}

