name: Test on close
on:
  pull_request:
    types: 
      - closed
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{toJSON(github.event.pull_request.labels)}}"
