name: Test on close
on:
  pull_request:
    types: 
      - closed
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - run: |
          echo "${{toJSON(github.event)}}"
