name: Preview
on:
  repository_dispatch:
    types: [preview-command]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps: 
      - name: test variables
        run: |
          echo "${{toJSON(github.event.client_payload.slash_command)}}"
