name: Preview
on:
  repository_dispatch:
    types: [preview-command]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps: 
      - name: test variables
        
        run: |
          echo ${{toJSON(github.event.client_payload.slash_command)}}
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ‘1.18.4’
      - name: Install dependencies
        run: |
          go get -u golang.org/x/lint/golint
          go vendor
      - name: Build
        run: go build .

      - name: Run vet & lint
        run: |
          go vet .
          golint .

