name: Push changes
on: 
  - push
permissions:
  repository-projects: write-all
jobs:
  check:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check out put
        id: check-output
        run: |
          MINOR_VERSION=$(echo "1.4.3" | sed -E 's/(.[0-9]+){1}$/.x/')
          echo "MINOR=$MINOR_VERSION">> "$GITHUB_OUTPUT"
      - name: value
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.TOKEN}}
          branch: ${{ steps.check-output.outputs.MINOR }}
