name: Push changes
on: 
  push:
     tags: 
       - "*" 
permissions: write-all
jobs:
  check:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check github object
        run: |
          echo "${{github.event.tag.name}}"
