name: Teardown Preview Link
on:
  pull_request:
    types:
      - closed
jobs:
  teardown:
    if: contains(github.event.pull_request.labels.*.name, preview-link)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to gcloud
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload-identity-provider: projects/1069571329272/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider
          service_account: github-actions-gar@mathgaps-dev-b044f.iam.gserviceaccount.com
      - name: Authenticate to GKE
        uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: primary
          location: australia-southeast1-a
      - run: |
          kubectl delete PreviewLink ${{ github.repository }}-${{ github.event.client_payload.slash_command.args.named.pr }} -n schools