name: Test GCP connection
on:
  push:
    tags: 
      - "*"
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{secrets.GCP_CRED}}
      - name: Authenticate to GKE 
        uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: primary
          location: australia-southeast1-a
      - run: |
          kubectl get pods
